// frontend/src/app/layout.tsx
'use client'; // <-- ADD THIS DIRECTIVE if not already there, as useAuthStore is a client hook

import { Inter } from 'next/font/google';
import './globals.css';
import { useEffect } from 'react'; // <-- ADD THIS IMPORT
import { useAuthStore } from '@/store/authStore'; // <-- ADD THIS IMPORT

const inter = Inter({ subsets: ['latin'] });

// export const metadata = { // COMMENT OUT OR REMOVE METADATA FOR CLIENT COMPONENTS
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initializeAuth = useAuthStore((state) => state.initializeAuth);

  useEffect(() => {
    initializeAuth();
  }, [initializeAuth]); // Re-run if initializeAuth function itself changes

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
